# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiscrap', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='MyTask',
        ),
    ]
